<TagsScreen>:
    name: ScreenNames.TAGS

    # Root
    BoxLayout:
        orientation: 'vertical'
        spacing: 10
        Label:
            size_hint: (1, None)
            text: 'tags_screen'

            height: "35dp"
            color: 0, 0, 0, 1
        Button:
            text: lang.get('back_btn')
            height: "70dp"

            on_release:
                root.manager.change_screen(ScreenNames.ENTRIES, "right")