<TagsScreen>:
    name: root.manager.tags_screen

    # Root
    BoxLayout:
        orientation: 'vertical'
        spacing: 10
        Label:
            size_hint: (1, None)
            text: 'tags_screen'

            height: "35dp"
            color: 0, 0, 0, 1
        Button:
            text: lang.get('back_btn')
            height: "70dp"

            on_release:
                root.manager.change_screen(root.manager.entries_screen, "right")